# Generated by Django 5.1.1 on 2024-09-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='mood_intensity',
        ),
    ]
