# Generated by Django 5.1.1 on 2024-09-18 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_mood_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='mood_intensity',
            field=models.IntegerField(default=0),
        ),
    ]
