# Generated by Django 5.1.1 on 2024-10-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_productform_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productform',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
